data:
  root_path: '/root/data/'
  data_path: 'unnorm_data.csv'
  output_field: 'Target'
  
  random_sample_from_each_pt: True
  equal_sample: True
  time_steps_len: &time_steps_len 4
  min_time_steps: 20
  sampled_steps:  16

  data_split: [0.7,0.1,0.2]
  scale: True

  batch_size: 150
  num_workers: 3
  drop_last: False
  pin_memory: False

model:
  name: BaseTransformer
  params:
    input_dim: 170
    time_steps_len: *time_steps_len

    random_embed: True
    pos_embed_requires_grad: True

    d_model: 512
    nhead: 8
    num_layers: 5
    dropout_prob: 0.1
    output_dim: 1

training_param:
  warmup_epochs: 10
  max_epochs: 50
  warmup_start_lr: 1.0e-8
  eta_min: 1.0e-8

  optimizer: AdamW
  params:
    beta_1: 0.9
    beta_2: 0.99
    lr: 5.0e-4
    weight_decay: 1.0e-5
    
loss:
  - name: GaussianLoss
    params: {}
    weight: 1.
  - name: MSELoss
    params: {}
    weight: 1.